### ISSUE TITLE
body 안에 body 를 중복으로 선언하면 안됩니다

### ISSUE THREAD

**Issue by ziponia** [2wisdom/elice-ai-track#1]
https://github.com/2wisdom/elice-ai-track/blob/50b0b7407c92ad903aa30aae548407866eb77c20/resume/resume.html#L50-L55

_잘못 된 예_

```html
<body>
   <body>
      ...
  </body>
</body>
```

_올바른 예_

```html
<body>
   ....
</body>
```

**Comment by 2wisdom** [comment]
good
